### ISSUE TITLE
How to setup on OrangePi?

### ISSUE THREAD

**Issue by Mqxx** [lancard/nginx-webui#10]
I am currently trying to set this up on my OrangePi but I get this error:
```
> docker compose up
[+] Running 0/1
 ⠧ ui Pulling                                                                                                      1.6s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

This is my compose file:
```yml
services:
  app:
    container_name: 'nginx.org'
    image: 'tiangolo/nginx-rtmp'
    ports:
      - '80:80'
      - '443:443'
      - '1935:1935'

    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/conf.d:/etc/nginx/conf.d:ro
      - ./data/custom:/data/nginx/custom:ro
      - ./data/logs:/data/logs
      - ./data/certs:/etc/letsencrypt

    restart: unless-stopped

  ui:
    container_name: 'nginx.org_ui'
    image: 'lancard/nginx-webui'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'

    volumes:
      - ./data/ui:/data
      - ./data/ui:/session
      - ./data/ui:/var/log/nginx
      - ./data/ui:/etc/letsencrypt
      - ./data/ui:/etc/logrotate.d
      
    restart: unless-stopped
```
